//map với file routerVue
//2 file có điểm tương đồng nhưng lười không cấu hình lại
export default [{
        showLabel: true,
        path: '/admin/home',
        name: 'home',
        title: 'Home',
        component: '',
        icon: 'fa-solid fa-house',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'admin-manage',
        title: 'Admin hệ thống',
        component: '',
        icon: 'fa-solid fa-list-check',
        role: '',
        children: [{
                path: 'khoa',
                code: 'account-management',
                title: 'Quản lý tài khoản',
                component: '',
                icon: 'fa-solid fa-user-secret',
                role: '',
            },
            {
                path: '',
                name: 'staff-management',
                title: 'Quản lý nhân viên',
                component: '',
                icon: 'fa-solid fa-person-rays',
                role: '',
            },
            {
                path: '',
                name: 'setting-admins',
                title: 'Cấu hình quản trị',
                component: '',
                icon: 'fa-solid fa-gears',
                role: '',
            },
            {
                path: '',
                name: 'setting-client',
                title: 'Cấu hình giao diện bán hàng',
                component: '',
                icon: 'fa-solid fa-mountain-sun',
                role: '',
            },
            {
                path: '',
                name: 'setting-properties',
                title: 'Thủ tục (pending)',
                component: '',
                icon: 'fa-solid fa-forward-step',
                role: '',
            },
            {
                path: '',
                name: 'service-administrator',
                title: 'Dịch vụ',
                component: '',
                icon: 'fa-solid fa-boxes-stacked',
                role: '',
            },
            {
                path: '',
                name: 'history',
                title: 'LỊCH SỬ',
                component: '',
                icon: 'fa-solid fa-file-waveform',
                role: '',
            },
        ]
    },
    {
        path: '',
        name: 'product-manager',
        title: 'SẢN PHẨM',
        component: '',
        icon: 'fa-brands fa-cotton-bureau',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'branches-managers',
        title: 'CHI NHÁNH',
        component: '',
        icon: 'fa-solid fa-code-branch',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'deliver-managers',
        title: 'VẬN CHUYỂN',
        component: '',
        icon: 'fa-solid fa-truck-ramp-box',
        role: '',
        children: [{
                path: '',
                name: 'deliver-order',
                title: 'ĐƠN HÀNG',
                component: '',
                icon: 'fa-solid fa-box-open',
                role: '',
            },
            {
                path: '',
                name: ' cooper-unit-order',
                title: 'ĐƠN VỊ HỢP TÁC',
                component: '',
                icon: 'fa-regular fa-handshake',
                role: '',
            }
        ]
    },
    {
        path: '',
        name: 'order-tracking',
        title: 'Theo dõi, quản lý đơn',
        component: '',
        icon: 'fa-solid fa-clipboard-list',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'customer-manager',
        title: 'KHÁCH HÀNG',
        component: '',
        icon: 'fa-solid fa-id-card',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'warehouse-manager',
        title: 'KHO',
        component: '',
        icon: 'fa-solid fa-warehouse',
        role: '',
        children: []
    },
    {
        path: '',
        name: 'web-client',
        title: 'WEB',
        component: '',
        icon: 'fa-brands fa-shopify',
        role: '',
        children: [{
                path: '',
                name: 'news',
                title: 'Tin tức',
                component: '',
                icon: 'fa-regular fa-newspaper',
                role: '',
            },
            {
                path: '',
                name: 'ads',
                title: 'Quản cáo',
                component: '',
                icon: 'fa-brands fa-adn',
                role: '',
            },
            {
                path: '',
                name: 'gift',
                title: 'MÃ GIẢM GIÁ',
                component: '',
                icon: 'fa-solid fa-gift',
                role: '',
            },
        ]
    },
    {
        path: '',
        name: 'reports',
        title: 'BÁO CÁO',
        component: '',
        icon: 'fa-solid fa-chart-line',
        role: '',
        children: []
    },
]