//map với file routerVue
//2 file có điểm tương đồng nhưng lười không cấu hình lại
export default [{
        showLabel: true,
        name: 'home',
        title: 'Home',
        component: '',
        icon: 'fa-solid fa-house',
        role: '',
        children: []
    },
    {
        code: 'sub_admin',
        title: 'Admin hệ thống',
        component: '',
        icon: 'fa-solid fa-list-check',
        role: ['ADMIN'],
        children: [{
                name: 'accountManagement',
                title: 'Quản lý tài khoản',
                component: '',
                icon: 'fa-solid fa-user-secret',
                role: '',
                name: 'accountManagement',
            },
            {
                name: 'accountManagement',
                title: 'Quản lý nhân viên',
                component: '',
                icon: 'fa-solid fa-person-rays',
                role: '',
            },
            {
                name: 'accountManagement',
                title: 'Cấu hình quản trị',
                component: '',
                icon: 'fa-solid fa-gears',
                role: '',
            },
            // {
            //     // name: 'setting-client',
            //     name: 'accountManagement',
            //     title: 'Cấu hình giao diện bán hàng',
            //     component: '',
            //     icon: 'fa-solid fa-mountain-sun',
            //     role: '',
            // },
            {
                // name: 'setting-properties',
                name: 'accountManagement',
                title: 'Thủ tục (pending)',
                component: '',
                icon: 'fa-solid fa-forward-step',
                role: '',
            },
            {
                // name: 'service-administrator',
                name: 'accountManagement',
                title: 'Dịch vụ',
                component: '',
                icon: 'fa-solid fa-boxes-stacked',
                role: '',
            },
            {
                // name: 'history',
                name: 'accountManagement',
                title: 'LỊCH SỬ',
                component: '',
                icon: 'fa-solid fa-file-waveform',
                role: '',
            },
        ]
    },
    {
        // name: 'product-manager',
        code: 'product-manager',
        title: 'SẢN PHẨM',
        component: '',
        icon: 'fa-brands fa-cotton-bureau',
        role: '',
        children: []
    },
    {
        // name: 'branches-managers',
        code: 'branches-managers',
        title: 'CHI NHÁNH',
        component: '',
        icon: 'fa-solid fa-code-branch',
        role: '',
        children: []
    },
    {
        code: 'deliver-managers',
        title: 'VẬN CHUYỂN',
        component: '',
        icon: 'fa-solid fa-truck-ramp-box',
        role: '',
        children: [{
                // name: 'deliver-order',
                name: '',
                title: 'ĐƠN HÀNG',
                component: '',
                icon: 'fa-solid fa-box-open',
                role: '',
            },
            {
                // name: ' cooper-unit-order',
                name: '',
                title: 'ĐƠN VỊ HỢP TÁC',
                component: '',
                icon: 'fa-regular fa-handshake',
                role: '',
            }
        ]
    },
    {
        // name: 'order-tracking',
        code: 'order-tracking',
        title: 'Theo dõi, quản lý đơn',
        component: '',
        icon: 'fa-solid fa-clipboard-list',
        role: '',
        children: []
    },
    {
        // name: 'customer-manager',
        code: 'customer-manager',
        title: 'KHÁCH HÀNG',
        component: '',
        icon: 'fa-solid fa-id-card',
        role: '',
        children: []
    },
    {
        // name: 'warehouse-manager',
        code: 'warehouse-manager',
        title: 'KHO',
        component: '',
        icon: 'fa-solid fa-warehouse',
        role: '',
        children: []
    },
    {
        code: 'web-client',
        title: 'WEB',
        component: '',
        icon: 'fa-brands fa-shopify',
        role: '',
        children: [{
                // name: 'menu',
                name: '',
                title: 'Menu',
                component: '',
                icon: "fa-solid fa-list",
                role: '',
            },
            {
                // name: 'news',
                name: '',
                title: 'Tin tức',
                component: '',
                icon: 'fa-regular fa-newspaper',
                role: '',
            },
            {
                // name: 'ads',
                name: '',
                title: 'Quản cáo',
                component: '',
                icon: 'fa-brands fa-adn',
                role: '',
            },
            {
                // name: 'gift',
                name: '',
                title: 'MÃ GIẢM GIÁ',
                component: '',
                icon: 'fa-solid fa-gift',
                role: '',
            },
        ]
    },
    {
        code: 'reports',
        title: 'BÁO CÁO',
        component: '',
        icon: 'fa-solid fa-chart-line',
        role: '',
        children: []
    },
    {
        code: 'adminFeedback',
        title: 'Phản hồi',
        component: '',
        icon: 'fa-solid fa-lines-leaning',
        role: ['FEEDBACK'],
        children: [{
                name: '',
                // name: 'denounce',
                title: 'Tố cáo',
                component: '',
                icon: 'fa-regular fa-flag',
                role: '',
            },
            {
                name: '',
                // name: 'feedback-products',
                title: 'Phản hồi sản phẩm',
                component: '',
                icon: 'a-regular fa-comment',
                role: '',
            },
            {
                name: '',
                // name: 'feedback-app',
                title: 'Phản hồi ứng dụng',
                component: '',
                icon: 'fa-regular fa-message',
                role: '',
            },
            {
                name: 'manageFeedback',
                title: 'Quản lý chung',
                component: '',
                icon: "fa-solid fa-sliders",
                role: '',
            },
        ]
    },
]